### ISSUE TITLE
Gists are dead

### ISSUE THREAD

**Issue by gbrl** [bsodmike/upgrade_rails_3.2.12_to_4.0.0.beta1#1]
It appears the code for this script is no longer online. Have a copy somewhere? :D

**Comment by bsodmike** [comment]
Tracked em down mate,

1. https://gist.github.com/bsodmike/5132812
2. https://gist.github.com/bsodmike/5136839

Wow, that was a serious bit of deja vu.  It's my Birthday today too 🍰 have a good one :D

**Comment by gbrl** [comment]
Thanks very much and….

*~H~A~P~P~Y~   ~B~I~R~T~H~D~A~Y~!~!~!~*
